name: Build and publish

on:
  - push
  - pull_request

jobs:
  test-build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: buildah bud -t okinta/iqfeed-keep-alive .

  publish:
    needs:
      - test-build-image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: okinta/iqfeed-keep-alive
          tags: latest
